<?php

namespace furyfire\chip8;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-05 at 14:33:38.
 */
class MemoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Memory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Memory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers furyfire\chip8\Memory::setMemory
     * @todo   Implement testSetMemory().
     */
    public function testSetMemory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers furyfire\chip8\Memory::getMemory
     * @todo   Implement testGetMemory().
     */
    public function testGetMemory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers furyfire\chip8\Memory::getByte
     * @todo   Implement testGetByte().
     */
    public function testGetByte()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers furyfire\chip8\Memory::setByte
     * @todo   Implement testSetByte().
     */
    public function testSetByte()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers furyfire\chip8\Memory::getInstruction
     * @todo   Implement testGetInstruction().
     */
    public function testGetInstruction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
